SessionConObjetos/Models/ErrorViewModel.cs
namespace SessionConObjetos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SessionConObjetos/Models/Restaurante.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SessionConObjetos.Models
{
    [Table("restaurantes")]
    public class Restaurante
    {
        [Key]
        [Column("id")]
        public int IdRestaurante { get; set; }
        [Column("nombre_restaurante")]
        public string Nombre_restaurante { get; set; }

        [Column("direccion")]
        public string Direccion { get; set; }

        [Column("telefono")]
        public int Telefono { get; set; }

        [Column("id_categoria")]
        public int Id_categoria { get; set; }

        [Column("imagen")]
        public string Imagen { get; set; }


    }
}

SessionConObjetos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SessionConObjetos.Models;
using System.Diagnostics;

namespace SessionConObjetos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SessionConObjetos/Controllers/RestauranteController.cs
using Microsoft.AspNetCore.Mvc;
using SessionConObjetos.Extensions;
using SessionConObjetos.Models;
using SessionConObjetos.Repositories;

namespace SessionConObjetos.Controllers
{
    public class RestauranteController : Controller
    {
        private RepositoryRestaurantes repo;
        public RestauranteController(RepositoryRestaurantes repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            List<Restaurante> restaurantesTotal = this.repo.GetRestaurantes();
            return View(restaurantesTotal);
        }

        public IActionResult GuardarSession(int idrest)
        {
            if (idrest != null)
            {
                Restaurante restaurante = this.repo.FindRestaurante(idrest);
                List<Restaurante> restaurantesSession;
                if (HttpContext.Session.GetObject<List<Restaurante>>("ListaObjetos") != null)
                {
                    restaurantesSession = HttpContext.Session.GetObject<List<Restaurante>>("ListaObjetos");
                }
                else
                {
                    restaurantesSession = new List<Restaurante>();
                }
                restaurantesSession.Add(restaurante);
                HttpContext.Session.SetObject("ListaObjetos", restaurantesSession);
            }
          
            return RedirectToAction("Index");

        }

        public IActionResult RestaurantesAlmacenados()
        {
            return View();
        }
    }
}

SessionConObjetos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SessionConObjetos/Views/Restaurante/Index.cshtml
@model IEnumerable<SessionConObjetos.Models.Restaurante>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="Restaurante" asp-action="RestaurantesAlmacenados" class="btn btn-warning">Restaurantes almacenados</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdRestaurante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_restaurante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id_categoria)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdRestaurante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre_restaurante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Id_categoria)
            </td>
            <td>
               <img src="~/images/@item.Imagen" style="width:200px;height:100px;"/>
            </td>
            <td>
                 <a asp-controller="Restaurante" asp-action="GuardarSession" asp-route-idrest="@item.IdRestaurante" class="btn btn-success">Añadir a la Session</a>
            </td>
        </tr>
}
    </tbody>
</table>

SessionConObjetos/Views/Restaurante/RestaurantesAlmacenados.cshtml
@using SessionConObjetos.Extensions;
@{
    List<Restaurante> restaurantes = Context.Session.GetObject<List<Restaurante>>("ListaObjetos");
}
@if(restaurantes != null)
{
<table class="table table-info">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Telefono</th>
            <th>Imagen</th>
        </tr>
    </thead>
    <tbody>
            @foreach(Restaurante rest in restaurantes)
            {
                <tr>
                    <td>@rest.Nombre_restaurante</td>
                    <td>@rest.Direccion</td>
                    <td>@rest.Telefono</td>
                    <td> <img src="~/images/@rest.Imagen" style="width:200px;height:100px;" /></td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h1>No hay restaurantes Almacenados</h1>
}

SessionConObjetos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SessionConObjetos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SessionConObjetos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SessionConObjetos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurante" asp-action="Index">Restaurantes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SessionConObjetos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>